---
name: "Setup Ciao"
author: Yevhen Fabizhevskyi
description: "This action installs Ciao CLI tool."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "Ciao version."
    required: false
    default: "1.23.0-m1"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'Windows' }}
      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
      shell: sh
    - name: Collect info
      id: info
      run: |
        ciao_installed=$(if command -v ciao >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "ciao-installed=${ciao_installed}" >> "$GITHUB_OUTPUT"
        bin_path="${GITHUB_WORKSPACE}/ciao"
        mkdir -p "${bin_path}"
        echo "ciao-path=${bin_path}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Download Ciao
      if: ${{ steps.info.outputs.ciao-installed == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ciao-lang/ciao
        ref: v${{ inputs.version }}
        fetch-depth: 1
        path: ciao
    - name: Install Ciao
      if: ${{ steps.info.outputs.ciao-installed == 'false' }}
      run: |
        ./ciao-boot.sh local-install
        echo "${{ steps.info.outputs.ciao-path }}/build/bin" >> "$GITHUB_PATH"
      shell: sh
      working-directory: ${{ steps.info.outputs.ciao-path }}
