---
name: "Setup Ciao"
author: Yevhen Fabizhevskyi
description: "This action installs Ciao CLI tool."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "Ciao version."
    required: false
    default: "1.23.0-m1"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'Windows' }}
      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
      shell: sh
    - name: Collect info
      id: info
      if: ${{ runner.os != 'Windows' }}
      run: |
        CIAO_INSTALLED=$(if command -v ciao >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "CIAO_INSTALLED=${CIAO_INSTALLED}" >> "$GITHUB_OUTPUT"
        bin_path="${GITHUB_WORKSPACE}/ciao"
        mkdir -p "${bin_path}"
        echo "CIAO_PATH=${bin_path}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Download Ciao
      if: ${{ runner.os != 'Windows' && steps.info.outputs.CIAO_INSTALLED == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: ciao-lang/ciao
        ref: v${{ inputs.version }}
        fetch-depth: 1
        path: ciao
    - name: Install Ciao
      if: ${{ runner.os != 'Windows' && steps.info.outputs.CIAO_INSTALLED == 'false' }}
      run: |
        ./ciao-boot.sh local-install
        echo "${{ steps.info.outputs.CIAO_PATH }}/build/bin" >> "$GITHUB_PATH"
      shell: sh
      working-directory: ${{ steps.info.outputs.CIAO_PATH }}
