---
name: "Setup Ciao"
author: Yevhen Fabizhevskyi
description: "This action installs Ciao CLI tool."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: Ciao version. Defaults to the latest version.
    required: false
    default: "latest"
  force:
    description: |
      If "false" skips installation if ciao is already installed. If "true"
      installs ciao in any case. Defaults to "false".
    required: false
    default: "false"
outputs:
  installed:
    description: Whether umka was installed or not.
    value: "${{ steps.install-ciao.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: |
        if [ "${INPUT_FORCE}" = "false" ] && command -v ciao >/dev/null 2>&1; then
          bin_installed="true"
        else
          bin_installed="false"
        fi
        echo "bin-installed=${bin_installed}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Setup emacs
      uses: jcs090218/setup-emacs@v2
    - name: Install Ciao
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-ciao
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: |
        curl https://ciao-lang.org/boot -sSfL | sh -s -- \
          get devenv \
          --release=${INPUT_VERSION}

        for dir in $HOME/.ciaoroot/*/; do
          if [ -d "${dir}" ]; then
            echo "${dir}/build/bin" >> "$GITHUB_PATH"
          fi
        done
      shell: sh
