---
name: "Setup Ciao"
author: Yevhen Fabizhevskyi
description: "This action installs Ciao CLI tool."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: Ciao version. Defaults to the latest version.
    required: false
    default: "latest"
  force:
    description: |
      If "false" skips installation if ciao is already installed. If "true"
      installs ciao in any case. Defaults to "false".
    required: false
    default: "false"
outputs:
  installed:
    description: Whether umka was installed or not.
    value: "${{ steps.install-ciao.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: |
        if [ "${INPUT_FORCE}" = "false" ] && command -v ciao >/dev/null 2>&1; then
          bin_installed="true"
        else
          bin_installed="false"
        fi
        echo "bin-installed=${bin_installed}" >> "$GITHUB_OUTPUT"

        bin_dir="$(date +%s)"
        echo "bin-dir=${bin_dir}" >> "$GITHUB_OUTPUT"

        bin_path="$GITHUB_WORKSPACE/${bin_dir}"
        echo "bin-path=${bin_path}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Download Ciao
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: "ciao-lang/ciao"
        ref: ${{ inputs.version == 'latest' && 'master' || format('v{0}', inputs.version) }}
        fetch-depth: 1
        path: ${{ steps.info.outputs.bin-dir }}
    - name: Install Ciao
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-ciao
      run: |
        ./ciao-boot.sh local-install
        echo "$(pwd)/build/bin" >> "$GITHUB_PATH"
      shell: sh
      working-directory: "${{ steps.info.outputs.bin-path }}"
#    - name: Install Ciao
#      if: ${{ steps.info.outputs.bin-installed == 'false' }}
#      id: install-ciao
#      env:
#        INPUT_VERSION: "${{ inputs.version }}"
#      run: |
#        export HOME=$RUNNER_TEMP
#        curl https://ciao-lang.org/boot -sSfL | sh -s -- \
#          --prebuilt-bin \
#          local-install \
#          --release=${INPUT_VERSION}
#
#        arch_dir="${{ runner.os == 'Linux' && 'LINUXx86_64' || (runner.os == 'macOS' && 'DARWINaarch64' || 'Win32x86_64') }}"
#
#        for dir in $RUNNER_TEMP/.ciaoroot/*/; do
#          if [ -d "${dir}" ]; then
#            echo "${dir}build/bin" >> "$GITHUB_PATH"
#            # echo "CIAOROOT=${dir}" >> "$GITHUB_ENV"
#            objs_dir="${dir}build/eng/ciaoengine/objs"
#            echo "CIAOENGINE=${objs_dir}/ciaoengine" >> "$GITHUB_ENV"
#          fi
#        done
#      shell: sh
