---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  setup-ciao:
    name: Setup Ciao
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        version:
          ["1.22.0-m7", "1.22.0-m6", "1.22.0-m5", "1.22.0-m4", "1.22.0-m3"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup Ciao
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Run command
        run: ciao list
